# docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://budgy_user:budgy_password@db:5432/budgy_development"

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "budgy_development"
      POSTGRES_USER: "budgy_user"
      POSTGRES_PASSWORD: "budgy_password"

